//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_details
    {
        public long course_id { get; set; }
        public long class_id { get; set; }
        public long subject_id { get; set; }
        public long teacher_id { get; set; }
        public long action_by { get; set; }
        public System.DateTime action_date { get; set; }
        public Nullable<long> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> is_combine { get; set; }
    
        public virtual CLASS_INFO CLASS_INFO { get; set; }
        public virtual SUBJECT_INFO SUBJECT_INFO { get; set; }
        public virtual teachers_info teachers_info { get; set; }
    }
}
