//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_INFO()
        {
            this.COURSE_TAKEN = new HashSet<COURSE_TAKEN>();
            this.RESULT_TBL = new HashSet<RESULT_TBL>();
        }
    
        public long STD_ID { get; set; }
        public long STD_ROLL { get; set; }
        public string STD_NAME { get; set; }
        public string STD_ADDRESS { get; set; }
        public string STD_FATHER_NAME { get; set; }
        public string STD_MOTHER_NAME { get; set; }
        public Nullable<int> STD_FATHER_CONTACT { get; set; }
        public Nullable<int> STD_MOTHER_CONTACT { get; set; }
        public Nullable<int> STD_CONTACT { get; set; }
        public string REMARKS { get; set; }
        public long ACTION_BY { get; set; }
        public System.DateTime ACTION_DATE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int IS_ACTIVE { get; set; }
        public long CLASS_ID { get; set; }
        public string GENDER { get; set; }
        public string RELIGION { get; set; }
    
        public virtual CLASS_INFO CLASS_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_TAKEN> COURSE_TAKEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULT_TBL> RESULT_TBL { get; set; }
    }
}
