//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBJECT_INFO()
        {
            this.course_details = new HashSet<course_details>();
            this.COURSE_TAKEN = new HashSet<COURSE_TAKEN>();
            this.RESULT_TBL = new HashSet<RESULT_TBL>();
        }
    
        public long SUB_ID { get; set; }
        public string SUB_NAME { get; set; }
        public long CLASS_ID { get; set; }
        public int TOTAL_MARKS { get; set; }
        public Nullable<int> CREATIVE_MARKS { get; set; }
        public Nullable<int> MCQ_MARKS { get; set; }
        public Nullable<int> PRACTICAL_MARKS { get; set; }
        public long ACTION_BY { get; set; }
        public System.DateTime ACTION_DATE { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string REMARKS { get; set; }
        public int IS_ACTIVE { get; set; }
        public string SUB_CODE { get; set; }
        public Nullable<long> COMBINE_SUB { get; set; }
        public string GROUP_CATEGORY { get; set; }
    
        public virtual CLASS_INFO CLASS_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_details> course_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_TAKEN> COURSE_TAKEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULT_TBL> RESULT_TBL { get; set; }
    }
}
