//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teachers_info()
        {
            this.course_details = new HashSet<course_details>();
        }
    
        public long teacher_id { get; set; }
        public string teacher_name { get; set; }
        public string address { get; set; }
        public int contact_no { get; set; }
        public string gender { get; set; }
        public string religion { get; set; }
        public string designation { get; set; }
        public long user_level { get; set; }
        public Nullable<int> is_active { get; set; }
        public long action_by { get; set; }
        public System.DateTime action_date { get; set; }
        public Nullable<long> update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_details> course_details { get; set; }
        public virtual USER_LEVEL_INFO USER_LEVEL_INFO { get; set; }
    }
}
