//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PASS_CHANGE_HST
    {
        public long CHANGE_ID { get; set; }
        public long USER_ID { get; set; }
        public string NEW_PASSWORD { get; set; }
        public string OLD_PASSWORD { get; set; }
        public System.DateTime CHANGE_DATE { get; set; }
    
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
