//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public long USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public long USER_LEVEL_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public decimal MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string USER_PHOTO { get; set; }
        public short LOGIN_ATTEMPT { get; set; }
        public Nullable<System.DateTime> DATE_PASSWORD_CHANGE { get; set; }
        public Nullable<System.DateTime> ACTION_DT { get; set; }
        public Nullable<long> ACTION_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DT { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public int IS_DELETED { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
    
        public virtual USER_LEVEL_INFO USER_LEVEL_INFO { get; set; }
        public virtual USER_PASS_CHANGE_HST USER_PASS_CHANGE_HST { get; set; }
    }
}
